version: '3.8'

services:
  app:
    build: .
    ports:
      - "443:443"  # Проброс порта для Go-приложения
    depends_on:
      - db
    volumes:
      - .:/app
    

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Проброс порта для Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # Тома для сохранения данных
volumes:
  pgdata: