version: '3.8'

services:
  app:
    build: .
    ports:
      - "443:443"  # Проброс порта для Go-приложения
    depends_on:
      - db
    volumes:
      - .:/app
    

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Проброс порта для Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data